index:
    path: /
    controller: App\Controller\IndexController::index
    
ingredients:
    path: /ingredients
    controller: App\Controller\IngredientController::index
    
ingredient_edit:
    path: /ingredient/{id}
    controller: App\Controller\IngredientController::edit
    methods: GET|POST
    
ingredient_new:
    path: /ingredient
    controller: App\Controller\IngredientController::new
    methods: GET|POST
    
ingredient_delete:
    path: /ingredient/delete/{id}
    controller: App\Controller\IngredientController::delete
    methods: POST
    
pizzas:
    path: /pizzas
    controller: App\Controller\PizzaController::index
    
pizza_edit:
    path: /pizza/{id}
    controller: App\Controller\PizzaController::edit
    methods: GET|POST
    
pizza_new:
    path: /pizza
    controller: App\Controller\PizzaController::new
    methods: GET|POST
    
pizza_delete:
    path: /pizza/delete/{id}
    controller: App\Controller\PizzaController::delete
    methods: POST
    
pizza_ingredients:
    path: /pizza/{id}/ingredients
    controller: App\Controller\PizzaController::ingredients
    methods: GET
    
pizza_ingredient_add:
    path: /pizza/{pizzaid}/ingredient/add/{ingredientid}
    controller: App\Controller\PizzaController::addIngredient
    methods: POST
    
pizza_ingredient_remove:
    path: /pizza/{pizzaid}/ingredient/remove/{ingredientid}
    controller: App\Controller\PizzaController::removeIngredient
    methods: POST